<a href="https://colab.research.google.com/github/souravk03/Machine-Learning-404/blob/main/EDA_I.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/aug_train.csv')[[	"enrollee_id",	"city_development_index"	,"training_hours"	,"target"]]

## 1. How big data is

In [ ]:
df.shape

(19158, 4)

## 2. How does the data look like

In [ ]:

df.sample(2)

      enrollee_id  city_development_index  training_hours  target
2319        13231                   0.727             254     0.0
9348        24460                   0.743             180     0.0

## 3. What is the data type of column

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19158 entries, 0 to 19157
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   enrollee_id             19158 non-null  int64
 1   city_development_index  19158 non-null  float64
 2   training_hours          19158 non-null  int64
 3   target                  19158 non-null  float64
dtypes: float64(2), int64(2)
memory usage: 598.8 KB

## 4. Find the missing value if any

In [ ]:
df.isnull().sum()

enrollee_id               0
city_development_index    0
training_hours            0
target                    0
dtype: int64

## 5. How does the data look mathmatically

In [ ]:
df.describe()

        enrollee_id  city_development_index  training_hours        target
count  19158.000000            19158.000000    19158.000000  19158.000000
mean   16875.358179                0.828848       65.366896      0.249348
std     9616.292592                0.123362       60.058462      0.432647
min        1.000000                0.448000        1.000000      0.000000
25%     8554.250000                0.740000       23.000000      0.000000
50%    16982.500000                0.903000       47.000000      0.000000
75%    25169.750000                0.920000       88.000000      0.000000
max    33380.000000                0.949000      336.000000      1.000000

## 6. Are there any duplicate data

In [ ]:
df.duplicated().sum()

np.int64(0)

## 7. What is the correlation between the columns

In [ ]:
df.corr()

,enrollee_id,city_development_index,training_hours,target
enrollee_id,1.000000,-0.040455,0.000998,0.049475
city_development_index,-0.040455,1.000000,0.001920,-0.341665
training_hours,0.000998,0.001920,1.000000,-0.021577
target,0.049475,-0.341665,-0.021577,1.000000

In [ ]:
df.corr()['target']

enrollee_id               0.049475
city_development_index   -0.341665
training_hours           -0.021577
target                    1.000000
Name: target, dtype: float64