<a href="https://colab.research.google.com/github/souravk03/Machine-Learning-404/blob/main/Fetching_data_from_API.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import requests
import pandas as pd
url = "https://bhagavad-gita3.p.rapidapi.com/v2/chapters/"

querystring = {"skip":"0","limit":"18"}

headers = {
	"x-rapidapi-key": "650e38d5f8msh4e527fee9ffa54cp1ca7e6jsn549f9da92432",
	"x-rapidapi-host": "bhagavad-gita3.p.rapidapi.com"
}

response = requests.get(url, headers=headers, params=querystring)

tempdf=pd.DataFrame(response.json())[['id','name','name_translated','verses_count','chapter_number','name_meaning']]

In [12]:
tempdf

,id,name,name_translated,verses_count,chapter_number,name_meaning
0,1,अर्जुनविषादयोग,Arjuna Visada Yoga,47,1,Arjuna's Dilemma
1,2,सांख्ययोग,Sankhya Yoga,72,2,Transcendental Knowledge
2,3,कर्मयोग,Karma Yoga,43,3,Path of Selfless Service
3,4,ज्ञानकर्मसंन्यासयोग,Jnana Karma Sanyasa Yoga,42,4,Path of Knowledge and the Disciplines of Action
4,5,कर्मसंन्यासयोग,Karma Sanyasa Yoga,29,5,Path of Renunciation
5,6,ध्यानयोग,Dhyana Yoga,47,6,Path of Meditation
6,7,ज्ञानविज्ञानयोग,Gyaan Vigyana Yoga,30,7,Self-Knowledge and Enlightenment
7,8,अक्षरब्रह्मयोग,Akshara Brahma Yoga,28,8,Path of the Eternal God
8,9,राजविद्याराजगुह्ययोग,Raja Vidya Yoga,34,9,Yoga through the King of Sciences
9,10,विभूतियोग,Vibhooti Yoga,42,10,Yoga through Appreciating the Infinite Opulenc...
10,11,विश्वरूपदर्शनयोग,Vishwaroopa Darshana Yoga,55,11,Yoga through Beholding the Cosmic Form of God
11,12,भक्तियोग,Bhakti Yoga,20,12,The Yoga of Devotion
12,13,क्षेत्र-क्षेत्रज्ञविभागयोग,Ksetra Ksetrajna Vibhaaga Yoga,35,13,Yoga through Distinguishing the Field and the ...
13,14,गुणत्रयविभागयोग,Gunatraya Vibhaga Yoga,27,14,Yoga through Understanding the Three Modes of ...
14,15,पुरुषोत्तमयोग,Purushottama Yoga,20,15,The Yoga of the Supreme Divine Personality
15,16,दैवासुरसम्पद्विभागयोग,Daivasura Sampad Vibhaga Yoga,24,16,Yoga through Discerning the Divine and Demonia...
16,17,श्रद्धात्रयविभागयोग,Sraddhatraya Vibhaga Yoga,28,17,Yoga through Discerning the Three Divisions of...
17,18,मोक्षसंन्यासयोग,Moksha Sanyaas Yoga,78,18,Yoga through the Perfection of Renunciation an...

In [14]:
df=pd.DataFrame()
df

Empty DataFrame
Columns: []
Index: []

In [16]:
tempdf.to_csv('/content/drive/MyDrive/Colab Notebooks/BhagavadGita.csv')